name: Flight Check Agent
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  
env:
  # מאפשר שימוש בגרסאות Node שלא נחשבות ל-Default הבטוח של GitHub כרגע
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: 'true'

jobs:
  run-agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm install
      - run: node index.js
